sort array by localeCompare
js-tasks-ru/js-20210921_kostya-igm pull request #2
Opened 2021-09-25 22:34 UTC by KonstantinBiryukov

2021-09-25 22:35 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-09-26 03:50 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2021-09-26 04:22 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2021-09-27 10:04 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return arr.slice().sort((a, b) => {
в данном решении есть дубликаты кода, это нужно исправить

2021-09-27 10:04 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    fields.forEach(field => {
проверьте можно ли данный цикл заменить на метод массива `includes`?
возможно это упростит код?

2021-09-27 10:05 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +  for (let [key, value] of Object.entries(obj)) {
а тут точно `let`?

2021-09-27 10:05 UTC, dosandk requested changes
посмотрите комментарии,
решение `sortStrings` следует поправить

2021-09-27 14:52 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2021-09-28 12:34 UTC, dosandk approved these changes
good 👍

2021-09-28 12:35 UTC, merged